{{- if not (eq .Values.enabled "plumbing") }}
{{- range $ns := .Values.clusterGroup.namespaces }}

{{- if empty $.Values.clusterGroup.operatorgroupExcludes }}


  {{- if kindIs "map" $ns }}
  {{- range $k, $v := $ns }}{{- /* We loop here even though the map has always just one key */}}

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ $k }}-operator-group
  namespace: {{ $k }}
spec:
  targetNamespaces:
  - {{ $k }}
  {{- end }}{{- /* range $k, $v := $ns */}}

  {{- else if kindIs "string" $ns }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ . }}-operator-group
  namespace: {{ . }}
spec:
  targetNamespaces:
  - {{ . }}
  {{- end }} {{- /* if kindIs "string" $ns */}}
  
---
{{- else if not (has .  $.Values.clusterGroup.operatorgroupExcludes) }}

  {{- if kindIs "map" $ns }}
  {{- range $k, $v := $ns }}{{- /* We loop here even though the map has always just one key */}}

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ $k }}-operator-group
  namespace: {{ $k }}
spec:
  targetNamespaces:
  - {{ $k }}
  {{- end }}{{- /* range $k, $v := $ns */}}

  {{- else if kindIs "string" $ns }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ . }}-operator-group
  namespace: {{ . }}
spec:
  targetNamespaces:
  - {{ . }}
  {{- end }} {{- /* if kindIs "string" $ns */}}
---
{{- end }}

{{- end }}
{{- end }}
