{{- if (eq .Values.enabled "plumbing") }}
{{- $namespace := cat $.Values.global.pattern $.Values.clusterGroup.name | replace " " "-" }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterGroup.targetCluster | kebabcase }}-secret
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "100"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ .Values.clusterGroup.targetCluster | kebabcase }}-secret
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
      data:
        name: {{ .Values.clusterGroup.targetCluster }}
        server: https://api.{{ .Values.global.clusterDomain }}:6443
        config: |
          {
            "bearerToken": {{ "{{ .kubeBearer | toString | quote }}" }},
            "tlsClientConfig": {
              "insecure": false,
              "caData": {{ "{{ .kubeCA | toString | quote }}" }}
            }
          }
  data:
  - secretKey: kubeBearer
    remoteRef:
      key: {{ $.Values.clusterGroup.hostedSite.bearer_secret_key }}
      property: bearerToken
  - secretKey: kubeCA
    remoteRef:
      key: {{ $.Values.clusterGroup.hostedSite.ca_secret_key }}
      property: b64content
{{- end }}
